### ISSUE TITLE
Issue during initial dev/build

### ISSUE THREAD

**Issue by hailwood** [jelicanin/silverstripe-htmleditorfield-content-templates#4]
```
[Emergency] Uncaught InvalidArgumentException: YamlFixture::__construct(): Fixture path "/app/vendor/fractas/canned-content/tests/fixtures.yml" not found
```

The issue comes from here https://github.com/fractaslabs/silverstripe-canned-content/blob/master/src/CannedContent.php#L135

As the tests directory is ignored in the export via the `.gitattributes` directory.

Need to either check if the file exists, move the file out of tests, or remove the preload all together.

**Comment by jelicanin** [comment]
Thanx @hailwood 
Issue fixed
